import random

class Player:
    def __init__(self, name):
        self.name = name
        self.health = 100
        self.attack = 10

    def is_alive(self):
        return self.health > 0

    def take_damage(self, damage):
        self.health -= damage

    def attack_enemy(self, enemy):
        damage = random.randint(0, self.attack)
        enemy.take_damage(damage)
        print(f'{self.name} attacks {enemy.name} for {damage} damage.')

class Enemy:
    def __init__(self, name, health, attack):
        self.name = name
        self.health = health
        self.attack = attack

    def is_alive(self):
        return self.health > 0

    def take_damage(self, damage):
        self.health -= damage

    def attack_player(self, player):
        damage = random.randint(0, self.attack)
        player.take_damage(damage)
        print(f'{self.name} attacks {player.name} for {damage} damage.')

def battle(player, enemy):
    while player.is_alive() and enemy.is_alive():
        player.attack_enemy(enemy)
        if enemy.is_alive():
            enemy.attack_player(player)

    if player.is_alive():
        print(f'{player.name} wins!')
    else:
        print(f'{enemy.name} wins!')

player_name = input("Enter your character's name: ")
player = Player(player_name)
enemy = Enemy("Dragon", 50, 15)

print(f'A wild {enemy.name} appears!')
print("Battle Start!")

battle(player, enemy)
